### ISSUE TITLE
[html5 history] Click back doesn't work

### ISSUE THREAD

**Issue by ghost** [anmonteiro/aemette#3]
I think there is bug in `history.cljs`, click back doesn't work at all. After some inspection, the error is at function `(defn disable-erroneous-popstate!`. It looks perfectly fine to me, but don't know why it doesn't work. 

Tested on Chrome.

**Comment by anmonteiro** [comment]
fixed aa08fcf95f36b5e76a87881bf7eb20fac0c9fee0

**Comment by ghost** [comment]
thanks
